# window.opacity = 0.8
[keyboard]
bindings = [
{ key = "l", mods = "Control", action = "ReceiveChar" },
]
[env]
TERM = "xterm-256color"

[general]

import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
